"""first migration

Revision ID: e113dbddb829
Revises: 
Create Date: 2022-06-05 19:02:15.528012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e113dbddb829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_id'), 'brand', ['id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('owner_category', sa.String(length=100), nullable=True),
    sa.Column('category_code', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('product_sub_type', sa.String(length=100), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=False),
    sa.Column('prescription', sa.String(length=50), nullable=False),
    sa.Column('pack_price', sa.Float(precision=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('salt_composition', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_brand_id'), 'product', ['brand_id'], unique=False)
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_info', sa.Text(), nullable=True),
    sa.Column('when_to_use', sa.String(length=200), nullable=True),
    sa.Column('how_to_use', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_attribute_id'), 'product_attribute', ['id'], unique=False)
    op.create_index(op.f('ix_product_attribute_product_id'), 'product_attribute', ['product_id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.Column('offer_price', sa.Float(precision=5), nullable=True),
    sa.Column('offer_start_date', sa.DateTime(), nullable=True),
    sa.Column('offer_end_date', sa.DateTime(), nullable=True),
    sa.Column('product_attribute_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_attribute_id'], ['product_attribute.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_id'), 'pricing', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_product_attribute_id'), 'pricing', ['product_attribute_id'], unique=False)
    op.create_index(op.f('ix_pricing_product_id'), 'pricing', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_product_id'), table_name='pricing')
    op.drop_index(op.f('ix_pricing_product_attribute_id'), table_name='pricing')
    op.drop_index(op.f('ix_pricing_id'), table_name='pricing')
    op.drop_table('pricing')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_product_attribute_product_id'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_id'), table_name='product_attribute')
    op.drop_table('product_attribute')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_index(op.f('ix_product_brand_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_brand_id'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
